### ISSUE TITLE
[Tracking] http-client change to support isahc metrics

### ISSUE THREAD

**Issue by asaaki** [asaaki/opentelemetry-surf#2]
PR: https://github.com/http-rs/http-client/pull/56

Once this is accepted and merged, also https://github.com/http-rs/surf needs a bump eventually.

After that we can officially support isahc-metrics reliably.

-----

TODOs:

- [x] http-client PR merged
- [x] http-client released including the change
- [x] surf's http-client dependency bumped

**Comment by asaaki** [comment]
`http-client` updated: https://github.com/http-rs/http-client/blob/v6.3.0/src/isahc.rs

Still waiting for `surf` 2.2 to be released: https://github.com/http-rs/surf/milestone/3

**Comment by asaaki** [comment]
([track changes] which need to include a http-client version bump to 6.3+)

[track changes]: https://github.com/http-rs/surf/compare/v2.1.0...main

**Comment by asaaki** [comment]
Changes included in 37e43372e97e3f7108684d8c679acc6cd2eb1835.

TODO:
- [ ] verify that it works

**Comment by asaaki** [comment]
Works.
